module Hammer
  class ContentProxy
    include Hammer::FindingFiles
    @@variables = { }

    def initialize(source_dir = nil, filename = nil)
      @@variables[:current_parser_filename] = filename if filename
      @@variables[:current_parser_source_dir] = source_dir if source_dir
    end

    def contentful
      @contentful ||= Hammer::ContentfulHelper.new(
        Settings.contentful,
        'default',
        self
      )
    end

    def markdown(text)
      Hammer::MarkdownParser.new.parse(text) if text
    end

    def path(file)
      find_file(file)
    end

    # hack to return "registered variables" and "smart errors"
    def method_missing(method_name, *arguments, &block)
      @@variables[method_name] || error(method_name.to_s)
    end

    def error(name)
      ex = SmartException.new(
        "Variable '#{name}' doesn't exists. Probably you misspelled or forgot \
        to define it.",
        text: "Undefined variable #{name}. See below list of pre-defined variables:",
        list: @@variables.keys - ['autogenerated_content_files'] + ['contentful']
      )
      raise fill_exception(ex)
    end

    def fill_exception(exeption, backtrace_point = 'TEMPLATE')
      exeption.source_path = [current_parser_source_dir,
                              '/',
                              current_parser_filename].join
      exeption.line = find_file_in_backtrace(backtrace_point)
      exeption.input_directory = current_parser_source_dir
      exeption
    end

    def find_file_in_backtrace(point)
      line = Thread.current.backtrace.find{ |x| x.match(point) }
      match = line.match(/:(\d+)/)
      match ? match[1].to_i : nil
    end

    class << self
      def register_variable(name, value)
        @@variables[name] = value
      end

      def unregister_variable(name)
        @@variables.delete(name)
      end

      def add_paths(paths)
        @@variables['autogenerated_content_files'] ||= []
        @@variables['autogenerated_content_files'].concat(paths)
      end

      def find_file(filename)
        return nil unless @@variables['autogenerated_content_files']
        @@variables['autogenerated_content_files'].select do |path|
          path.match(filename)
        end.max_by(&:length)
      end
    end
  end
end